// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package admin

// ApiKey defines model for ApiKey.
type ApiKey struct {
	// ApiKey This is set once only after creation.  The user will need to record it.
	ApiKey       *string          `json:"api_key,omitempty"`
	CreateTime   Timestamp        `json:"create_time"`
	Creator      UserName         `json:"creator"`
	Description  *string          `json:"description,omitempty"`
	Name         ApiKeyName       `json:"name"`
	Node         *NodeName        `json:"node,omitempty"`
	Organization OrganizationName `json:"organization"`

	// Secret This is set only after creation.
	Secret     *string    `json:"secret,omitempty"`
	UpdateTime *Timestamp `json:"update_time,omitempty"`
}

// ApiKeyCreate defines model for ApiKeyCreate.
type ApiKeyCreate struct {
	Description  *string          `json:"description,omitempty"`
	Organization OrganizationName `json:"organization"`
}

// ApiKeyData defines model for ApiKeyData.
type ApiKeyData struct {
	// ApiKey This is set once only after creation.  The user will need to record it.
	ApiKey       *string          `json:"api_key,omitempty"`
	Description  *string          `json:"description,omitempty"`
	Node         *NodeName        `json:"node,omitempty"`
	Organization OrganizationName `json:"organization"`

	// Secret This is set only after creation.
	Secret *string `json:"secret,omitempty"`
}

// ApiKeyName defines model for ApiKeyName.
type ApiKeyName = string

// ApiKeyPage defines model for ApiKeyPage.
type ApiKeyPage struct {
	ApiKeys       *[]ApiKeyName `json:"api-keys,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// Bak defines model for Bak.
type Bak struct {
	// Bak The age public key.
	Bak string `json:"bak"`

	// Id Optional ID for the backup key.
	Id *string `json:"id,omitempty"`
}

// Email defines model for Email.
type Email = string

// Keys defines model for Keys.
type Keys struct {
	Engine struct {
		Identity string `json:"identity"`
	} `json:"engine"`
	Node struct {
		Identity string `json:"identity"`
	} `json:"node"`
	Signer struct {
		Identity  string `json:"identity"`
		Recipient string `json:"recipient"`
	} `json:"signer"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	CreateTime Timestamp  `json:"create_time"`
	Creator    UserName   `json:"creator"`
	UpdateTime *Timestamp `json:"update_time,omitempty"`
}

// Node defines model for Node.
type Node struct {
	Baks        *[]Bak     `json:"baks,omitempty"`
	Connector   bool       `json:"connector"`
	CreateTime  Timestamp  `json:"create_time"`
	Creator     string     `json:"creator"`
	Description *string    `json:"description,omitempty"`
	Host        string     `json:"host"`
	Keys        *Keys      `json:"keys,omitempty"`
	Name        NodeName   `json:"name"`
	Port        *int       `json:"port,omitempty"`
	UpdateTime  *Timestamp `json:"update_time,omitempty"`
	Updater     *string    `json:"updater,omitempty"`
}

// NodeData defines model for NodeData.
type NodeData struct {
	Baks        *[]Bak  `json:"baks,omitempty"`
	Connector   bool    `json:"connector"`
	Creator     string  `json:"creator"`
	Description *string `json:"description,omitempty"`
	Host        string  `json:"host"`
	Keys        *Keys   `json:"keys,omitempty"`
	Port        *int    `json:"port,omitempty"`
	Updater     *string `json:"updater,omitempty"`
}

// NodeName defines model for NodeName.
type NodeName = string

// NodePage defines model for NodePage.
type NodePage struct {
	NextPageToken *string `json:"next_page_token,omitempty"`
	Nodes         *[]Node `json:"nodes,omitempty"`
}

// Organization defines model for Organization.
type Organization struct {
	CreateTime  Timestamp        `json:"create_time"`
	Creator     UserName         `json:"creator"`
	DisplayName *string          `json:"display_name,omitempty"`
	Name        OrganizationName `json:"name"`
	Permissions *[]Permission    `json:"permissions,omitempty"`
	Slug        *string          `json:"slug,omitempty"`
	UpdateTime  *Timestamp       `json:"update_time,omitempty"`

	// Users `OUTPUT ONLY`. Keys are UserName, values are `admin` or `member`.
	Users *map[string]string `json:"users,omitempty"`
}

// OrganizationData defines model for OrganizationData.
type OrganizationData struct {
	DisplayName *string       `json:"display_name,omitempty"`
	Permissions *[]Permission `json:"permissions,omitempty"`
	Slug        *string       `json:"slug,omitempty"`

	// Users `OUTPUT ONLY`. Keys are UserName, values are `admin` or `member`.
	Users *map[string]string `json:"users,omitempty"`
}

// OrganizationName defines model for OrganizationName.
type OrganizationName = string

// OrganizationPage defines model for OrganizationPage.
type OrganizationPage struct {
	NextPageToken *string         `json:"next_page_token,omitempty"`
	Organizations *[]Organization `json:"organizations,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// Permission An organization (or possibly individual user) may or may not have a given permission.
type Permission = interface{}

// Timestamp defines model for Timestamp.
type Timestamp = string

// Treasury defines model for Treasury.
type Treasury struct {
	// Api Valid URL
	Api            *Url             `json:"api,omitempty"`
	CreateTime     Timestamp        `json:"create_time"`
	Creator        UserName         `json:"creator"`
	Description    *string          `json:"description,omitempty"`
	InitialVersion *string          `json:"initial_version,omitempty"`
	Name           TreasuryName     `json:"name"`
	Network        *string          `json:"network,omitempty"`
	Organization   OrganizationName `json:"organization"`
	Size           *int             `json:"size,omitempty"`
	Software       *string          `json:"software,omitempty"`
	UpdateTime     *Timestamp       `json:"update_time,omitempty"`
}

// TreasuryCreate defines model for TreasuryCreate.
type TreasuryCreate struct {
	Api            *string           `json:"api,omitempty"`
	Description    *string           `json:"description,omitempty"`
	InitialVersion *string           `json:"initial_version,omitempty"`
	Mainnet        *bool             `json:"mainnet,omitempty"`
	Organization   *OrganizationName `json:"organization,omitempty"`
	Size           *int              `json:"size,omitempty"`
}

// TreasuryData defines model for TreasuryData.
type TreasuryData struct {
	// Api Valid URL
	Api            *Url             `json:"api,omitempty"`
	Description    *string          `json:"description,omitempty"`
	InitialVersion *string          `json:"initial_version,omitempty"`
	Network        *string          `json:"network,omitempty"`
	Organization   OrganizationName `json:"organization"`
	Size           *int             `json:"size,omitempty"`
	Software       *string          `json:"software,omitempty"`
}

// TreasuryName defines model for TreasuryName.
type TreasuryName = string

// TreasuryPage defines model for TreasuryPage.
type TreasuryPage struct {
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Treasuries    *[]Treasury `json:"treasuries,omitempty"`
}

// Url Valid URL
type Url = string

// User defines model for User.
type User struct {
	CreateTime Timestamp `json:"create_time"`
	Creator    UserName  `json:"creator"`

	// DisplayName Concatenation of first and last name
	DisplayName *string  `json:"display_name,omitempty"`
	Emails      *[]Email `json:"emails,omitempty"`
	FirstName   *string  `json:"first_name,omitempty"`
	LastName    *string  `json:"last_name,omitempty"`
	Name        UserName `json:"name"`

	// Organizations `OUTPUT ONLY`. Keys are OrganizationName, values are `admin` or `member`
	Organizations *map[string]string `json:"organizations,omitempty"`
	PrimaryEmail  *Email             `json:"primary_email,omitempty"`
	UpdateTime    *Timestamp         `json:"update_time,omitempty"`
}

// UserData defines model for UserData.
type UserData struct {
	// DisplayName Concatenation of first and last name
	DisplayName *string  `json:"display_name,omitempty"`
	Emails      *[]Email `json:"emails,omitempty"`
	FirstName   *string  `json:"first_name,omitempty"`
	LastName    *string  `json:"last_name,omitempty"`

	// Organizations `OUTPUT ONLY`. Keys are OrganizationName, values are `admin` or `member`
	Organizations *map[string]string `json:"organizations,omitempty"`
	PrimaryEmail  *Email             `json:"primary_email,omitempty"`
}

// UserName defines model for UserName.
type UserName = string

// UserPage defines model for UserPage.
type UserPage struct {
	NextPageToken *string `json:"next_page_token,omitempty"`
	Users         *[]User `json:"users,omitempty"`
}

// ListOrganizationsParams defines parameters for ListOrganizations.
type ListOrganizationsParams struct {
	// Users fetch users
	Users *bool `form:"users,omitempty" json:"users,omitempty"`
}

// GetOrganizationParams defines parameters for GetOrganization.
type GetOrganizationParams struct {
	// Users fetch users
	Users *bool `form:"users,omitempty" json:"users,omitempty"`
}

// ListTreasuriesParams defines parameters for ListTreasuries.
type ListTreasuriesParams struct {
	// Authorization Bear token
	Authorization *string `json:"Authorization,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Organizations fetch organizations
	Organizations *bool `form:"organizations,omitempty" json:"organizations,omitempty"`

	// ORGANIZATION Set this to comma separated list of organizations.  Only resources that belongs to given organizations will be returned.
	ORGANIZATION *string `json:"ORGANIZATION,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Organizations fetch organizations
	Organizations *bool `form:"organizations,omitempty" json:"organizations,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = ApiKeyCreate

// CreateTreasuryJSONRequestBody defines body for CreateTreasury for application/json ContentType.
type CreateTreasuryJSONRequestBody = TreasuryCreate

// UpdateTreasuryJSONRequestBody defines body for UpdateTreasury for application/json ContentType.
type UpdateTreasuryJSONRequestBody = Treasury
